//
//  BusinessInfo.swift
//  swe-project-app
//
//  Created by Hugh Do on 11/8/20.
//

import Foundation

struct Constants {
    static let categories = [
        "Barbershops & Hair Salons",
        "Restaurants",
        "Bars",
        "Transportation",
        "Banking & Finance",
        "Entertainment",
        "Accounting & Tax Services",
        "Auto",
        "Dentists & Orthodontists",
        "Education",
        "Health & Wellness",
        "Health Care",
        "Home Improvement",
        "Insurance",
        "Internet & Web Services",
        "Legal Services",
        "Travel",
        "Marketing & Advertising",
        "Pet Services",
        "Real Estate",
        "Nightlife",
        "Shopping & Retail",
        "Sports & Recreation",
        "Utilities"
    ]
    
    static let races = [
        "Cuban",
        "European",
        "Far East Asian",
        "Haitian",
        "Hispanic or Latino",
        "Indian",
        "Jamaican",
        "Jewish",
        "Mexican",
        "Middle Eastern",
        "Puerto Rican",
        "Russian",
        "Native Hawaiian or Pacific Islander",
        "North African",
        "Sub-Saharan African",
        "Southeast Asian",
        "White"
    ]
 
    static let fullStates = [
           "AL": "Alabama",
           "AK": "Alaska",
           "AS": "American Samoa",
           "AZ": "Arizona",
           "AR": "Arkansas",
           "CA": "California",
           "CO": "Colorado",
           "CT": "Connecticut",
           "DE": "Delaware",
           "DC": "District Of Columbia",
           "FM": "Federated States Of Micronesia",
           "FL": "Florida",
           "GA": "Georgia",
           "GU": "Guam",
           "HI": "Hawaii",
           "ID": "Idaho",
           "IL": "Illinois",
           "IN": "Indiana",
           "IA": "Iowa",
           "KS": "Kansas",
           "KY": "Kentucky",
           "LA": "Louisiana",
           "ME": "Maine",
           "MH": "Marshall Islands",
           "MD": "Maryland",
           "MA": "Massachusetts",
           "MI": "Michigan",
           "MN": "Minnesota",
           "MS": "Mississippi",
           "MO": "Missouri",
           "MT": "Montana",
           "NE": "Nebraska",
           "NV": "Nevada",
           "NH": "New Hampshire",
           "NJ": "New Jersey",
           "NM": "New Mexico",
           "NY": "New York",
           "NC": "North Carolina",
           "ND": "North Dakota",
           "MP": "Northern Mariana Islands",
           "OH": "Ohio",
           "OK": "Oklahoma",
           "OR": "Oregon",
           "PW": "Palau",
           "PA": "Pennsylvania",
           "PR": "Puerto Rico",
           "RI": "Rhode Island",
           "SC": "South Carolina",
           "SD": "South Dakota",
           "TN": "Tennessee",
           "TX": "Texas",
           "UT": "Utah",
           "VT": "Vermont",
           "VI": "Virgin Islands",
           "VA": "Virginia",
           "WA": "Washington",
           "WV": "West Virginia",
           "WI": "Wisconsin",
           "WY": "Wyoming"
    ]
    
    static let states = [
        "AK",
        "AL",
        "AR",
        "AS",
        "AZ",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "GA",
        "GU",
        "HI",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "ME",
        "MI",
        "MN",
        "MO",
        "MS",
        "MT",
        "NC",
        "ND" ,
        "NE",
        "NH",
        "NJ",
        "NM",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "PR",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VA",
        "VI",
        "VT",
        "WA",
        "WI",
        "WV",
        "WY"
    ]
}
