# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'swe-project-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swe-project-app

  # add the Firebase pod for Google Analytics


  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleMaps', '4.0.0'
  pod 'GooglePlaces', '4.0.0'



  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'swe-project-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swe-project-appUITests' do
    # Pods for testing
  end

end
